name: Build Android App with Java 17

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Make Gradle wrapper executable (optional)
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease  # Adjust the command based on your build requirements
